# Generated by Django 3.2.5 on 2021-07-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_index', models.AutoField(primary_key=True, serialize=False)),
                ('video_path', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_index', models.IntegerField(blank=True, null=True)),
                ('highlight_path', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('emotion_1', models.IntegerField(blank=True, null=True)),
                ('emotion_2', models.IntegerField(blank=True, null=True)),
                ('emotion_3', models.IntegerField(blank=True, null=True)),
                ('video_index', models.ForeignKey(blank=True, db_column='video_index', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.video')),
            ],
            options={
                'db_table': 'highlight',
            },
        ),
    ]
