version: '3'

services: 
    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./frontend:/app
        stdin_open: true
        expose: 
            - "3000"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 -t 0
        volumes:
            - ./static:/usr/src/app/staticfiles
        expose:
            - "8000"

    nginx:
      build:
        dockerfile: Dockerfile
        context: ./nginx
      container_name: nginx
      ports:
        - "80:80/tcp"
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./static:/staticfiles