# Generated by Django 3.2.5 on 2021-07-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='highlight',
            table='highlight',
        ),
    ]
